name: Build

on:
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'

jobs:

  Create_Build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm ci

      - name: === building three ===
        run: npm run build && npm run build-module && npm run build-examples

      - name: === Giving permission to build script ===
        run: chmod +x ./utils/three-production.sh

      - name: === Running build script ===
        run: sh ./utils/three-production.sh
      # - uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #       ssh-private-key: ${{ secrets.WEBA_BOT_SSH_KEY }}
      - name: Create pull request in weba/three
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.WEBA_BOT_PAT }}
        with:
          source_folder: 'output'
          destination_repo: 'webaverse/three'
          destination_folder: ''
          destination_base_branch: 'main'
          destination_head_branch: 'threejs-bump'
          user_email: 'bot@webaverse.com'
          user_name: 'Weba Bot'
          pull_request_reviewers: 'abeersaqib'

      - name: Create Pull Request in weba/three.js
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            build/three.module.js
            examples/jsm/*
            package.json
