name: CI

on:
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'

jobs:

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci

      - name: === Linting ===
        run: npm run lint

  unit:
    name: "Unit testing"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === Unit testing ===
        run: npm run test-unit

  e2e-windows:
    name: "E2E testing (Windows)"
    runs-on: windows-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === E2E testing ===
        run: npm run test-e2e

  e2e-linux:
    name: "E2E testing (Linux)"
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === E2E testing ===
        run: npm run test-e2e

  e2e-macos:
    name: "E2E testing (MacOS)"
    runs-on: macos-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === E2E testing ===
        run: npm run test-e2e

  e2e-cov:
    name: "Examples ready for release"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci

      - name: === Ready for release ===
        run: npm run test-e2e-cov
